// Code generated by MockGen. DO NOT EDIT.
// Source: internal/events/dashboard_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/events/dashboard_service.go -destination=internal/testutil/mocks/services/mock_dashboard_service.go -package=services -mock_names=DashboardService=MockDashboardService -exclude_interfaces=DashboardEventRepository,DashboardInviteRepository,DashboardRSVPRepository
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	events "github.com/lenaxia/tinyrsvp/internal/events"
	gomock "go.uber.org/mock/gomock"
)

// MockDashboardService is a mock of DashboardService interface.
type MockDashboardService struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardServiceMockRecorder
	isgomock struct{}
}

// MockDashboardServiceMockRecorder is the mock recorder for MockDashboardService.
type MockDashboardServiceMockRecorder struct {
	mock *MockDashboardService
}

// NewMockDashboardService creates a new mock instance.
func NewMockDashboardService(ctrl *gomock.Controller) *MockDashboardService {
	mock := &MockDashboardService{ctrl: ctrl}
	mock.recorder = &MockDashboardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardService) EXPECT() *MockDashboardServiceMockRecorder {
	return m.recorder
}

// GetDashboardStats mocks base method.
func (m *MockDashboardService) GetDashboardStats(ctx context.Context, userID int64) (*events.DashboardStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardStats", ctx, userID)
	ret0, _ := ret[0].(*events.DashboardStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardStats indicates an expected call of GetDashboardStats.
func (mr *MockDashboardServiceMockRecorder) GetDashboardStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardStats", reflect.TypeOf((*MockDashboardService)(nil).GetDashboardStats), ctx, userID)
}

// GetRecentActivity mocks base method.
func (m *MockDashboardService) GetRecentActivity(ctx context.Context, userID int64, limit int) ([]*events.ActivityItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentActivity", ctx, userID, limit)
	ret0, _ := ret[0].([]*events.ActivityItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentActivity indicates an expected call of GetRecentActivity.
func (mr *MockDashboardServiceMockRecorder) GetRecentActivity(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentActivity", reflect.TypeOf((*MockDashboardService)(nil).GetRecentActivity), ctx, userID, limit)
}
