// Code generated by MockGen. DO NOT EDIT.
// Source: internal/rsvp/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/rsvp/service.go -destination=internal/testutil/mocks/services/mock_rsvp_service.go -package=services -mock_names=Service=MockRSVPService -exclude_interfaces=InviteService,InviteRepository
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	models "github.com/lenaxia/tinyrsvp/internal/models"
	rsvp "github.com/lenaxia/tinyrsvp/internal/rsvp"
	gomock "go.uber.org/mock/gomock"
)

// MockRSVPService is a mock of Service interface.
type MockRSVPService struct {
	ctrl     *gomock.Controller
	recorder *MockRSVPServiceMockRecorder
	isgomock struct{}
}

// MockRSVPServiceMockRecorder is the mock recorder for MockRSVPService.
type MockRSVPServiceMockRecorder struct {
	mock *MockRSVPService
}

// NewMockRSVPService creates a new mock instance.
func NewMockRSVPService(ctrl *gomock.Controller) *MockRSVPService {
	mock := &MockRSVPService{ctrl: ctrl}
	mock.recorder = &MockRSVPServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRSVPService) EXPECT() *MockRSVPServiceMockRecorder {
	return m.recorder
}

// SubmitRSVP mocks base method.
func (m *MockRSVPService) SubmitRSVP(ctx context.Context, token string, req *rsvp.SubmitRSVPRequest) (*models.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitRSVP", ctx, token, req)
	ret0, _ := ret[0].(*models.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitRSVP indicates an expected call of SubmitRSVP.
func (mr *MockRSVPServiceMockRecorder) SubmitRSVP(ctx, token, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitRSVP", reflect.TypeOf((*MockRSVPService)(nil).SubmitRSVP), ctx, token, req)
}

// UpdateRSVP mocks base method.
func (m *MockRSVPService) UpdateRSVP(ctx context.Context, token string, req *rsvp.SubmitRSVPRequest) (*models.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRSVP", ctx, token, req)
	ret0, _ := ret[0].(*models.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRSVP indicates an expected call of UpdateRSVP.
func (mr *MockRSVPServiceMockRecorder) UpdateRSVP(ctx, token, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRSVP", reflect.TypeOf((*MockRSVPService)(nil).UpdateRSVP), ctx, token, req)
}
