// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handlers/admin.go
//
// Generated by this command:
//
//	mockgen -source=internal/handlers/admin.go -destination=internal/testutil/mocks/services/mock_admin_handler_services.go -package=services -mock_names=AdminDashboardService=MockAdminDashboardService,UserListService=MockUserListService -exclude_interfaces=AdminDashboardHandler,UserManagementHandler
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	admin "github.com/lenaxia/tinyrsvp/internal/admin"
	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminDashboardService is a mock of AdminDashboardService interface.
type MockAdminDashboardService struct {
	ctrl     *gomock.Controller
	recorder *MockAdminDashboardServiceMockRecorder
	isgomock struct{}
}

// MockAdminDashboardServiceMockRecorder is the mock recorder for MockAdminDashboardService.
type MockAdminDashboardServiceMockRecorder struct {
	mock *MockAdminDashboardService
}

// NewMockAdminDashboardService creates a new mock instance.
func NewMockAdminDashboardService(ctrl *gomock.Controller) *MockAdminDashboardService {
	mock := &MockAdminDashboardService{ctrl: ctrl}
	mock.recorder = &MockAdminDashboardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminDashboardService) EXPECT() *MockAdminDashboardServiceMockRecorder {
	return m.recorder
}

// GetAdminStats mocks base method.
func (m *MockAdminDashboardService) GetAdminStats(ctx context.Context) (*admin.AdminStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminStats", ctx)
	ret0, _ := ret[0].(*admin.AdminStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminStats indicates an expected call of GetAdminStats.
func (mr *MockAdminDashboardServiceMockRecorder) GetAdminStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminStats", reflect.TypeOf((*MockAdminDashboardService)(nil).GetAdminStats), ctx)
}

// MockUserListService is a mock of UserListService interface.
type MockUserListService struct {
	ctrl     *gomock.Controller
	recorder *MockUserListServiceMockRecorder
	isgomock struct{}
}

// MockUserListServiceMockRecorder is the mock recorder for MockUserListService.
type MockUserListServiceMockRecorder struct {
	mock *MockUserListService
}

// NewMockUserListService creates a new mock instance.
func NewMockUserListService(ctrl *gomock.Controller) *MockUserListService {
	mock := &MockUserListService{ctrl: ctrl}
	mock.recorder = &MockUserListServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserListService) EXPECT() *MockUserListServiceMockRecorder {
	return m.recorder
}

// CountUsers mocks base method.
func (m *MockUserListService) CountUsers(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockUserListServiceMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockUserListService)(nil).CountUsers), ctx)
}

// ListUsers mocks base method.
func (m *MockUserListService) ListUsers(ctx context.Context, limit, offset int) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, limit, offset)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserListServiceMockRecorder) ListUsers(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserListService)(nil).ListUsers), ctx, limit, offset)
}
