// Code generated by MockGen. DO NOT EDIT.
// Source: internal/templates/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/templates/service.go -destination=internal/testutil/mocks/services/mock_template_service.go -package=services -mock_names=Service=MockTemplateService
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	io "io"
	reflect "reflect"

	repositories "github.com/lenaxia/tinyrsvp/internal/db/repositories"
	models "github.com/lenaxia/tinyrsvp/internal/models"
	templates "github.com/lenaxia/tinyrsvp/internal/templates"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateService is a mock of Service interface.
type MockTemplateService struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateServiceMockRecorder
	isgomock struct{}
}

// MockTemplateServiceMockRecorder is the mock recorder for MockTemplateService.
type MockTemplateServiceMockRecorder struct {
	mock *MockTemplateService
}

// NewMockTemplateService creates a new mock instance.
func NewMockTemplateService(ctrl *gomock.Controller) *MockTemplateService {
	mock := &MockTemplateService{ctrl: ctrl}
	mock.recorder = &MockTemplateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateService) EXPECT() *MockTemplateServiceMockRecorder {
	return m.recorder
}

// CreateTemplate mocks base method.
func (m *MockTemplateService) CreateTemplate(ctx context.Context, template *models.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplate", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTemplate indicates an expected call of CreateTemplate.
func (mr *MockTemplateServiceMockRecorder) CreateTemplate(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplate", reflect.TypeOf((*MockTemplateService)(nil).CreateTemplate), ctx, template)
}

// DeleteTemplate mocks base method.
func (m *MockTemplateService) DeleteTemplate(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplate indicates an expected call of DeleteTemplate.
func (mr *MockTemplateServiceMockRecorder) DeleteTemplate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplate", reflect.TypeOf((*MockTemplateService)(nil).DeleteTemplate), ctx, id)
}

// GetComponentRenderer mocks base method.
func (m *MockTemplateService) GetComponentRenderer() *templates.ComponentRenderer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentRenderer")
	ret0, _ := ret[0].(*templates.ComponentRenderer)
	return ret0
}

// GetComponentRenderer indicates an expected call of GetComponentRenderer.
func (mr *MockTemplateServiceMockRecorder) GetComponentRenderer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentRenderer", reflect.TypeOf((*MockTemplateService)(nil).GetComponentRenderer))
}

// GetDefaultTemplate mocks base method.
func (m *MockTemplateService) GetDefaultTemplate(ctx context.Context, templateType models.TemplateType) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultTemplate", ctx, templateType)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultTemplate indicates an expected call of GetDefaultTemplate.
func (mr *MockTemplateServiceMockRecorder) GetDefaultTemplate(ctx, templateType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultTemplate", reflect.TypeOf((*MockTemplateService)(nil).GetDefaultTemplate), ctx, templateType)
}

// GetTemplate mocks base method.
func (m *MockTemplateService) GetTemplate(ctx context.Context, id int64) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplate", ctx, id)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplate indicates an expected call of GetTemplate.
func (mr *MockTemplateServiceMockRecorder) GetTemplate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplate", reflect.TypeOf((*MockTemplateService)(nil).GetTemplate), ctx, id)
}

// GetTemplateForEvent mocks base method.
func (m *MockTemplateService) GetTemplateForEvent(ctx context.Context, eventID int64, templateType models.TemplateType) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateForEvent", ctx, eventID, templateType)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateForEvent indicates an expected call of GetTemplateForEvent.
func (mr *MockTemplateServiceMockRecorder) GetTemplateForEvent(ctx, eventID, templateType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateForEvent", reflect.TypeOf((*MockTemplateService)(nil).GetTemplateForEvent), ctx, eventID, templateType)
}

// ListTemplates mocks base method.
func (m *MockTemplateService) ListTemplates(ctx context.Context, filters *repositories.TemplateFilters) ([]*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplates", ctx, filters)
	ret0, _ := ret[0].([]*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplates indicates an expected call of ListTemplates.
func (mr *MockTemplateServiceMockRecorder) ListTemplates(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplates", reflect.TypeOf((*MockTemplateService)(nil).ListTemplates), ctx, filters)
}

// PreviewTemplate mocks base method.
func (m *MockTemplateService) PreviewTemplate(ctx context.Context, req *templates.PreviewRequest) (*templates.PreviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewTemplate", ctx, req)
	ret0, _ := ret[0].(*templates.PreviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewTemplate indicates an expected call of PreviewTemplate.
func (mr *MockTemplateServiceMockRecorder) PreviewTemplate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewTemplate", reflect.TypeOf((*MockTemplateService)(nil).PreviewTemplate), ctx, req)
}

// RenderEmailTemplate mocks base method.
func (m *MockTemplateService) RenderEmailTemplate(ctx context.Context, eventID int64, templateType models.TemplateType, data any) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderEmailTemplate", ctx, eventID, templateType, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RenderEmailTemplate indicates an expected call of RenderEmailTemplate.
func (mr *MockTemplateServiceMockRecorder) RenderEmailTemplate(ctx, eventID, templateType, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderEmailTemplate", reflect.TypeOf((*MockTemplateService)(nil).RenderEmailTemplate), ctx, eventID, templateType, data)
}

// RenderRSVPPage mocks base method.
func (m *MockTemplateService) RenderRSVPPage(w io.Writer, event *models.Event, template *models.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderRSVPPage", w, event, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenderRSVPPage indicates an expected call of RenderRSVPPage.
func (mr *MockTemplateServiceMockRecorder) RenderRSVPPage(w, event, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderRSVPPage", reflect.TypeOf((*MockTemplateService)(nil).RenderRSVPPage), w, event, template)
}

// SetActive mocks base method.
func (m *MockTemplateService) SetActive(ctx context.Context, id int64, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockTemplateServiceMockRecorder) SetActive(ctx, id, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockTemplateService)(nil).SetActive), ctx, id, active)
}

// SetDefault mocks base method.
func (m *MockTemplateService) SetDefault(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefault", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefault indicates an expected call of SetDefault.
func (mr *MockTemplateServiceMockRecorder) SetDefault(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefault", reflect.TypeOf((*MockTemplateService)(nil).SetDefault), ctx, id)
}

// UpdateTemplate mocks base method.
func (m *MockTemplateService) UpdateTemplate(ctx context.Context, template *models.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplate", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTemplate indicates an expected call of UpdateTemplate.
func (mr *MockTemplateServiceMockRecorder) UpdateTemplate(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplate", reflect.TypeOf((*MockTemplateService)(nil).UpdateTemplate), ctx, template)
}
