// Code generated by MockGen. DO NOT EDIT.
// Source: internal/email/metrics.go
//
// Generated by this command:
//
//	mockgen -source=internal/email/metrics.go -destination=internal/testutil/mocks/other/mock_email_metrics.go -package=other -mock_names=Metrics=MockEmailMetrics
//

// Package other is a generated GoMock package.
package other

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailMetrics is a mock of Metrics interface.
type MockEmailMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockEmailMetricsMockRecorder
	isgomock struct{}
}

// MockEmailMetricsMockRecorder is the mock recorder for MockEmailMetrics.
type MockEmailMetricsMockRecorder struct {
	mock *MockEmailMetrics
}

// NewMockEmailMetrics creates a new mock instance.
func NewMockEmailMetrics(ctrl *gomock.Controller) *MockEmailMetrics {
	mock := &MockEmailMetrics{ctrl: ctrl}
	mock.recorder = &MockEmailMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailMetrics) EXPECT() *MockEmailMetricsMockRecorder {
	return m.recorder
}

// RecordBatchProcessed mocks base method.
func (m *MockEmailMetrics) RecordBatchProcessed(count int, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordBatchProcessed", count, duration)
}

// RecordBatchProcessed indicates an expected call of RecordBatchProcessed.
func (mr *MockEmailMetricsMockRecorder) RecordBatchProcessed(count, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBatchProcessed", reflect.TypeOf((*MockEmailMetrics)(nil).RecordBatchProcessed), count, duration)
}

// RecordEmailDequeued mocks base method.
func (m *MockEmailMetrics) RecordEmailDequeued() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordEmailDequeued")
}

// RecordEmailDequeued indicates an expected call of RecordEmailDequeued.
func (mr *MockEmailMetricsMockRecorder) RecordEmailDequeued() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEmailDequeued", reflect.TypeOf((*MockEmailMetrics)(nil).RecordEmailDequeued))
}

// RecordEmailFailed mocks base method.
func (m *MockEmailMetrics) RecordEmailFailed(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordEmailFailed", reason)
}

// RecordEmailFailed indicates an expected call of RecordEmailFailed.
func (mr *MockEmailMetricsMockRecorder) RecordEmailFailed(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEmailFailed", reflect.TypeOf((*MockEmailMetrics)(nil).RecordEmailFailed), reason)
}

// RecordEmailQueued mocks base method.
func (m *MockEmailMetrics) RecordEmailQueued() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordEmailQueued")
}

// RecordEmailQueued indicates an expected call of RecordEmailQueued.
func (mr *MockEmailMetricsMockRecorder) RecordEmailQueued() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEmailQueued", reflect.TypeOf((*MockEmailMetrics)(nil).RecordEmailQueued))
}

// RecordEmailSent mocks base method.
func (m *MockEmailMetrics) RecordEmailSent(duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordEmailSent", duration)
}

// RecordEmailSent indicates an expected call of RecordEmailSent.
func (mr *MockEmailMetricsMockRecorder) RecordEmailSent(duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEmailSent", reflect.TypeOf((*MockEmailMetrics)(nil).RecordEmailSent), duration)
}

// RecordProcessingError mocks base method.
func (m *MockEmailMetrics) RecordProcessingError(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordProcessingError", err)
}

// RecordProcessingError indicates an expected call of RecordProcessingError.
func (mr *MockEmailMetricsMockRecorder) RecordProcessingError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordProcessingError", reflect.TypeOf((*MockEmailMetrics)(nil).RecordProcessingError), err)
}

// RecordQueueSize mocks base method.
func (m *MockEmailMetrics) RecordQueueSize(size int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordQueueSize", size)
}

// RecordQueueSize indicates an expected call of RecordQueueSize.
func (mr *MockEmailMetricsMockRecorder) RecordQueueSize(size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordQueueSize", reflect.TypeOf((*MockEmailMetrics)(nil).RecordQueueSize), size)
}

// RecordRateLimitHit mocks base method.
func (m *MockEmailMetrics) RecordRateLimitHit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRateLimitHit")
}

// RecordRateLimitHit indicates an expected call of RecordRateLimitHit.
func (mr *MockEmailMetricsMockRecorder) RecordRateLimitHit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRateLimitHit", reflect.TypeOf((*MockEmailMetrics)(nil).RecordRateLimitHit))
}

// RecordRateLimitWait mocks base method.
func (m *MockEmailMetrics) RecordRateLimitWait(duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRateLimitWait", duration)
}

// RecordRateLimitWait indicates an expected call of RecordRateLimitWait.
func (mr *MockEmailMetricsMockRecorder) RecordRateLimitWait(duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRateLimitWait", reflect.TypeOf((*MockEmailMetrics)(nil).RecordRateLimitWait), duration)
}

// RecordRetryAttempt mocks base method.
func (m *MockEmailMetrics) RecordRetryAttempt(attempt int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRetryAttempt", attempt)
}

// RecordRetryAttempt indicates an expected call of RecordRetryAttempt.
func (mr *MockEmailMetricsMockRecorder) RecordRetryAttempt(attempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRetryAttempt", reflect.TypeOf((*MockEmailMetrics)(nil).RecordRetryAttempt), attempt)
}
