// Code generated by MockGen. DO NOT EDIT.
// Source: internal/admin/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/admin/service.go -destination=internal/testutil/mocks/other/mock_admin_counters.go -package=other -mock_names=UserCounter=MockUserCounter,EventCounter=MockEventCounter,InviteCounter=MockInviteCounter,AdminService=MockAdminService
//

// Package other is a generated GoMock package.
package other

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserCounter is a mock of UserCounter interface.
type MockUserCounter struct {
	ctrl     *gomock.Controller
	recorder *MockUserCounterMockRecorder
	isgomock struct{}
}

// MockUserCounterMockRecorder is the mock recorder for MockUserCounter.
type MockUserCounterMockRecorder struct {
	mock *MockUserCounter
}

// NewMockUserCounter creates a new mock instance.
func NewMockUserCounter(ctrl *gomock.Controller) *MockUserCounter {
	mock := &MockUserCounter{ctrl: ctrl}
	mock.recorder = &MockUserCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCounter) EXPECT() *MockUserCounterMockRecorder {
	return m.recorder
}

// CountUsers mocks base method.
func (m *MockUserCounter) CountUsers(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockUserCounterMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockUserCounter)(nil).CountUsers), ctx)
}

// MockEventCounter is a mock of EventCounter interface.
type MockEventCounter struct {
	ctrl     *gomock.Controller
	recorder *MockEventCounterMockRecorder
	isgomock struct{}
}

// MockEventCounterMockRecorder is the mock recorder for MockEventCounter.
type MockEventCounterMockRecorder struct {
	mock *MockEventCounter
}

// NewMockEventCounter creates a new mock instance.
func NewMockEventCounter(ctrl *gomock.Controller) *MockEventCounter {
	mock := &MockEventCounter{ctrl: ctrl}
	mock.recorder = &MockEventCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventCounter) EXPECT() *MockEventCounterMockRecorder {
	return m.recorder
}

// CountEvents mocks base method.
func (m *MockEventCounter) CountEvents(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEvents", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEvents indicates an expected call of CountEvents.
func (mr *MockEventCounterMockRecorder) CountEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEvents", reflect.TypeOf((*MockEventCounter)(nil).CountEvents), ctx)
}

// MockInviteCounter is a mock of InviteCounter interface.
type MockInviteCounter struct {
	ctrl     *gomock.Controller
	recorder *MockInviteCounterMockRecorder
	isgomock struct{}
}

// MockInviteCounterMockRecorder is the mock recorder for MockInviteCounter.
type MockInviteCounterMockRecorder struct {
	mock *MockInviteCounter
}

// NewMockInviteCounter creates a new mock instance.
func NewMockInviteCounter(ctrl *gomock.Controller) *MockInviteCounter {
	mock := &MockInviteCounter{ctrl: ctrl}
	mock.recorder = &MockInviteCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviteCounter) EXPECT() *MockInviteCounterMockRecorder {
	return m.recorder
}

// CountInvites mocks base method.
func (m *MockInviteCounter) CountInvites(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountInvites", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountInvites indicates an expected call of CountInvites.
func (mr *MockInviteCounterMockRecorder) CountInvites(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountInvites", reflect.TypeOf((*MockInviteCounter)(nil).CountInvites), ctx)
}
