// Code generated by MockGen. DO NOT EDIT.
// Source: internal/email/processor.go
//
// Generated by this command:
//
//	mockgen -source=internal/email/processor.go -destination=internal/testutil/mocks/other/mock_email_processor.go -package=other -exclude_interfaces=QueueProcessor
//

// Package other is a generated GoMock package.
package other

import (
	context "context"
	reflect "reflect"
	time "time"

	email "github.com/lenaxia/tinyrsvp/internal/email"
	gomock "go.uber.org/mock/gomock"
)

// MockSMTPSender is a mock of SMTPSender interface.
type MockSMTPSender struct {
	ctrl     *gomock.Controller
	recorder *MockSMTPSenderMockRecorder
	isgomock struct{}
}

// MockSMTPSenderMockRecorder is the mock recorder for MockSMTPSender.
type MockSMTPSenderMockRecorder struct {
	mock *MockSMTPSender
}

// NewMockSMTPSender creates a new mock instance.
func NewMockSMTPSender(ctrl *gomock.Controller) *MockSMTPSender {
	mock := &MockSMTPSender{ctrl: ctrl}
	mock.recorder = &MockSMTPSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSMTPSender) EXPECT() *MockSMTPSenderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSMTPSender) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSMTPSenderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSMTPSender)(nil).Close))
}

// Send mocks base method.
func (m *MockSMTPSender) Send(ctx context.Context, msg *email.SMTPMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSMTPSenderMockRecorder) Send(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSMTPSender)(nil).Send), ctx, msg)
}

// TestConnection mocks base method.
func (m *MockSMTPSender) TestConnection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockSMTPSenderMockRecorder) TestConnection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockSMTPSender)(nil).TestConnection), ctx)
}

// MockRateLimiter is a mock of RateLimiter interface.
type MockRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterMockRecorder
	isgomock struct{}
}

// MockRateLimiterMockRecorder is the mock recorder for MockRateLimiter.
type MockRateLimiterMockRecorder struct {
	mock *MockRateLimiter
}

// NewMockRateLimiter creates a new mock instance.
func NewMockRateLimiter(ctrl *gomock.Controller) *MockRateLimiter {
	mock := &MockRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiter) EXPECT() *MockRateLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockRateLimiter) Allow() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Allow indicates an expected call of Allow.
func (mr *MockRateLimiterMockRecorder) Allow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockRateLimiter)(nil).Allow))
}

// AvailableSlots mocks base method.
func (m *MockRateLimiter) AvailableSlots() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvailableSlots")
	ret0, _ := ret[0].(int)
	return ret0
}

// AvailableSlots indicates an expected call of AvailableSlots.
func (mr *MockRateLimiterMockRecorder) AvailableSlots() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvailableSlots", reflect.TypeOf((*MockRateLimiter)(nil).AvailableSlots))
}

// Record mocks base method.
func (m *MockRateLimiter) Record() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record")
}

// Record indicates an expected call of Record.
func (mr *MockRateLimiterMockRecorder) Record() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockRateLimiter)(nil).Record))
}

// Reset mocks base method.
func (m *MockRateLimiter) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockRateLimiterMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockRateLimiter)(nil).Reset))
}

// WaitTime mocks base method.
func (m *MockRateLimiter) WaitTime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitTime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// WaitTime indicates an expected call of WaitTime.
func (mr *MockRateLimiterMockRecorder) WaitTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitTime", reflect.TypeOf((*MockRateLimiter)(nil).WaitTime))
}
