// Code generated by MockGen. DO NOT EDIT.
// Source: internal/email/renderer.go
//
// Generated by this command:
//
//	mockgen -source=internal/email/renderer.go -destination=internal/testutil/mocks/other/mock_email_renderer.go -package=other
//

// Package other is a generated GoMock package.
package other

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTemplateRenderer is a mock of TemplateRenderer interface.
type MockTemplateRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateRendererMockRecorder
	isgomock struct{}
}

// MockTemplateRendererMockRecorder is the mock recorder for MockTemplateRenderer.
type MockTemplateRendererMockRecorder struct {
	mock *MockTemplateRenderer
}

// NewMockTemplateRenderer creates a new mock instance.
func NewMockTemplateRenderer(ctrl *gomock.Controller) *MockTemplateRenderer {
	mock := &MockTemplateRenderer{ctrl: ctrl}
	mock.recorder = &MockTemplateRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateRenderer) EXPECT() *MockTemplateRendererMockRecorder {
	return m.recorder
}

// LoadTemplates mocks base method.
func (m *MockTemplateRenderer) LoadTemplates() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTemplates")
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadTemplates indicates an expected call of LoadTemplates.
func (mr *MockTemplateRendererMockRecorder) LoadTemplates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTemplates", reflect.TypeOf((*MockTemplateRenderer)(nil).LoadTemplates))
}

// ReloadTemplates mocks base method.
func (m *MockTemplateRenderer) ReloadTemplates() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadTemplates")
	ret0, _ := ret[0].(error)
	return ret0
}

// ReloadTemplates indicates an expected call of ReloadTemplates.
func (mr *MockTemplateRendererMockRecorder) ReloadTemplates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadTemplates", reflect.TypeOf((*MockTemplateRenderer)(nil).ReloadTemplates))
}

// RenderHTML mocks base method.
func (m *MockTemplateRenderer) RenderHTML(ctx context.Context, templateName string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderHTML", ctx, templateName, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderHTML indicates an expected call of RenderHTML.
func (mr *MockTemplateRendererMockRecorder) RenderHTML(ctx, templateName, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderHTML", reflect.TypeOf((*MockTemplateRenderer)(nil).RenderHTML), ctx, templateName, data)
}

// RenderText mocks base method.
func (m *MockTemplateRenderer) RenderText(ctx context.Context, templateName string, data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderText", ctx, templateName, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderText indicates an expected call of RenderText.
func (mr *MockTemplateRendererMockRecorder) RenderText(ctx, templateName, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderText", reflect.TypeOf((*MockTemplateRenderer)(nil).RenderText), ctx, templateName, data)
}
