// Code generated by MockGen. DO NOT EDIT.
// Source: internal/middleware/rbac.go
//
// Generated by this command:
//
//	mockgen -source=internal/middleware/rbac.go -destination=internal/testutil/mocks/other/mock_middleware_rbac.go -package=other
//

// Package other is a generated GoMock package.
package other
