// Code generated by MockGen. DO NOT EDIT.
// Source: internal/jobs/archiver.go
//
// Generated by this command:
//
//	mockgen -source=internal/jobs/archiver.go -destination=internal/testutil/mocks/other/mock_jobs_event_service.go -package=other -mock_names=EventService=MockJobsEventService -exclude_interfaces=Archiver
//

// Package other is a generated GoMock package.
package other

import (
	context "context"
	reflect "reflect"

	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockJobsEventService is a mock of EventService interface.
type MockJobsEventService struct {
	ctrl     *gomock.Controller
	recorder *MockJobsEventServiceMockRecorder
	isgomock struct{}
}

// MockJobsEventServiceMockRecorder is the mock recorder for MockJobsEventService.
type MockJobsEventServiceMockRecorder struct {
	mock *MockJobsEventService
}

// NewMockJobsEventService creates a new mock instance.
func NewMockJobsEventService(ctrl *gomock.Controller) *MockJobsEventService {
	mock := &MockJobsEventService{ctrl: ctrl}
	mock.recorder = &MockJobsEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobsEventService) EXPECT() *MockJobsEventServiceMockRecorder {
	return m.recorder
}

// ArchiveEvent mocks base method.
func (m *MockJobsEventService) ArchiveEvent(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveEvent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveEvent indicates an expected call of ArchiveEvent.
func (mr *MockJobsEventServiceMockRecorder) ArchiveEvent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveEvent", reflect.TypeOf((*MockJobsEventService)(nil).ArchiveEvent), ctx, id)
}

// GetEventsToArchive mocks base method.
func (m *MockJobsEventService) GetEventsToArchive(ctx context.Context, daysAfterEvent int) ([]*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsToArchive", ctx, daysAfterEvent)
	ret0, _ := ret[0].([]*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsToArchive indicates an expected call of GetEventsToArchive.
func (mr *MockJobsEventServiceMockRecorder) GetEventsToArchive(ctx, daysAfterEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsToArchive", reflect.TypeOf((*MockJobsEventService)(nil).GetEventsToArchive), ctx, daysAfterEvent)
}
