// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/rsvp_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/rsvp_repository.go -destination=internal/testutil/mocks/repositories/mock_rsvp_repository.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	repositories "github.com/lenaxia/tinyrsvp/internal/db/repositories"
	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRSVPRepository is a mock of RSVPRepository interface.
type MockRSVPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRSVPRepositoryMockRecorder
	isgomock struct{}
}

// MockRSVPRepositoryMockRecorder is the mock recorder for MockRSVPRepository.
type MockRSVPRepositoryMockRecorder struct {
	mock *MockRSVPRepository
}

// NewMockRSVPRepository creates a new mock instance.
func NewMockRSVPRepository(ctrl *gomock.Controller) *MockRSVPRepository {
	mock := &MockRSVPRepository{ctrl: ctrl}
	mock.recorder = &MockRSVPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRSVPRepository) EXPECT() *MockRSVPRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRSVPRepository) Create(ctx context.Context, rsvp *models.RSVP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rsvp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRSVPRepositoryMockRecorder) Create(ctx, rsvp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRSVPRepository)(nil).Create), ctx, rsvp)
}

// GetByEventID mocks base method.
func (m *MockRSVPRepository) GetByEventID(ctx context.Context, eventID int64) ([]*models.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEventID", ctx, eventID)
	ret0, _ := ret[0].([]*models.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEventID indicates an expected call of GetByEventID.
func (mr *MockRSVPRepositoryMockRecorder) GetByEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEventID", reflect.TypeOf((*MockRSVPRepository)(nil).GetByEventID), ctx, eventID)
}

// GetByID mocks base method.
func (m *MockRSVPRepository) GetByID(ctx context.Context, id int64) (*models.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRSVPRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRSVPRepository)(nil).GetByID), ctx, id)
}

// GetByInviteID mocks base method.
func (m *MockRSVPRepository) GetByInviteID(ctx context.Context, inviteID int64) (*models.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInviteID", ctx, inviteID)
	ret0, _ := ret[0].(*models.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInviteID indicates an expected call of GetByInviteID.
func (mr *MockRSVPRepositoryMockRecorder) GetByInviteID(ctx, inviteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInviteID", reflect.TypeOf((*MockRSVPRepository)(nil).GetByInviteID), ctx, inviteID)
}

// GetByInviteIDs mocks base method.
func (m *MockRSVPRepository) GetByInviteIDs(ctx context.Context, inviteIDs []int64) ([]*models.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInviteIDs", ctx, inviteIDs)
	ret0, _ := ret[0].([]*models.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInviteIDs indicates an expected call of GetByInviteIDs.
func (mr *MockRSVPRepositoryMockRecorder) GetByInviteIDs(ctx, inviteIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInviteIDs", reflect.TypeOf((*MockRSVPRepository)(nil).GetByInviteIDs), ctx, inviteIDs)
}

// GetStats mocks base method.
func (m *MockRSVPRepository) GetStats(ctx context.Context, eventID int64) (*repositories.RSVPStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, eventID)
	ret0, _ := ret[0].(*repositories.RSVPStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockRSVPRepositoryMockRecorder) GetStats(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockRSVPRepository)(nil).GetStats), ctx, eventID)
}

// Update mocks base method.
func (m *MockRSVPRepository) Update(ctx context.Context, rsvp *models.RSVP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rsvp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRSVPRepositoryMockRecorder) Update(ctx, rsvp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRSVPRepository)(nil).Update), ctx, rsvp)
}
