// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/event_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/event_repository.go -destination=internal/testutil/mocks/repositories/mock_event_repository.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	repositories "github.com/lenaxia/tinyrsvp/internal/db/repositories"
	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// CountEvents mocks base method.
func (m *MockEventRepository) CountEvents(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEvents", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEvents indicates an expected call of CountEvents.
func (mr *MockEventRepositoryMockRecorder) CountEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEvents", reflect.TypeOf((*MockEventRepository)(nil).CountEvents), ctx)
}

// Create mocks base method.
func (m *MockEventRepository) Create(ctx context.Context, event *models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEventRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventRepository)(nil).Create), ctx, event)
}

// Delete mocks base method.
func (m *MockEventRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventRepository)(nil).Delete), ctx, id)
}

// DeleteComponentOverrides mocks base method.
func (m *MockEventRepository) DeleteComponentOverrides(ctx context.Context, eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComponentOverrides", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComponentOverrides indicates an expected call of DeleteComponentOverrides.
func (mr *MockEventRepositoryMockRecorder) DeleteComponentOverrides(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComponentOverrides", reflect.TypeOf((*MockEventRepository)(nil).DeleteComponentOverrides), ctx, eventID)
}

// GetByCreatorID mocks base method.
func (m *MockEventRepository) GetByCreatorID(ctx context.Context, creatorID int64) ([]*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCreatorID", ctx, creatorID)
	ret0, _ := ret[0].([]*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCreatorID indicates an expected call of GetByCreatorID.
func (mr *MockEventRepositoryMockRecorder) GetByCreatorID(ctx, creatorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCreatorID", reflect.TypeOf((*MockEventRepository)(nil).GetByCreatorID), ctx, creatorID)
}

// GetByFriendlyName mocks base method.
func (m *MockEventRepository) GetByFriendlyName(ctx context.Context, friendlyName string) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFriendlyName", ctx, friendlyName)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFriendlyName indicates an expected call of GetByFriendlyName.
func (mr *MockEventRepositoryMockRecorder) GetByFriendlyName(ctx, friendlyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFriendlyName", reflect.TypeOf((*MockEventRepository)(nil).GetByFriendlyName), ctx, friendlyName)
}

// GetByID mocks base method.
func (m *MockEventRepository) GetByID(ctx context.Context, id int64) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEventRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEventRepository)(nil).GetByID), ctx, id)
}

// GetByPublicID mocks base method.
func (m *MockEventRepository) GetByPublicID(ctx context.Context, publicID string) (*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPublicID", ctx, publicID)
	ret0, _ := ret[0].(*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPublicID indicates an expected call of GetByPublicID.
func (mr *MockEventRepositoryMockRecorder) GetByPublicID(ctx, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPublicID", reflect.TypeOf((*MockEventRepository)(nil).GetByPublicID), ctx, publicID)
}

// GetByStatus mocks base method.
func (m *MockEventRepository) GetByStatus(ctx context.Context, status models.EventStatus) ([]*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStatus", ctx, status)
	ret0, _ := ret[0].([]*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStatus indicates an expected call of GetByStatus.
func (mr *MockEventRepositoryMockRecorder) GetByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStatus", reflect.TypeOf((*MockEventRepository)(nil).GetByStatus), ctx, status)
}

// GetComponentOverrides mocks base method.
func (m *MockEventRepository) GetComponentOverrides(ctx context.Context, eventID int64) (*models.ComponentOverrides, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentOverrides", ctx, eventID)
	ret0, _ := ret[0].(*models.ComponentOverrides)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComponentOverrides indicates an expected call of GetComponentOverrides.
func (mr *MockEventRepositoryMockRecorder) GetComponentOverrides(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentOverrides", reflect.TypeOf((*MockEventRepository)(nil).GetComponentOverrides), ctx, eventID)
}

// GetEventsToArchive mocks base method.
func (m *MockEventRepository) GetEventsToArchive(ctx context.Context, daysAfterEvent int) ([]*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsToArchive", ctx, daysAfterEvent)
	ret0, _ := ret[0].([]*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsToArchive indicates an expected call of GetEventsToArchive.
func (mr *MockEventRepositoryMockRecorder) GetEventsToArchive(ctx, daysAfterEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsToArchive", reflect.TypeOf((*MockEventRepository)(nil).GetEventsToArchive), ctx, daysAfterEvent)
}

// List mocks base method.
func (m *MockEventRepository) List(ctx context.Context, filters repositories.ListFilters) ([]*models.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*models.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEventRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEventRepository)(nil).List), ctx, filters)
}

// ListWithStats mocks base method.
func (m *MockEventRepository) ListWithStats(ctx context.Context, filters repositories.ListFilters) ([]*models.EventWithStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithStats", ctx, filters)
	ret0, _ := ret[0].([]*models.EventWithStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithStats indicates an expected call of ListWithStats.
func (mr *MockEventRepositoryMockRecorder) ListWithStats(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithStats", reflect.TypeOf((*MockEventRepository)(nil).ListWithStats), ctx, filters)
}

// Update mocks base method.
func (m *MockEventRepository) Update(ctx context.Context, event *models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEventRepositoryMockRecorder) Update(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEventRepository)(nil).Update), ctx, event)
}

// UpdateComponentOverrides mocks base method.
func (m *MockEventRepository) UpdateComponentOverrides(ctx context.Context, eventID int64, overrides *models.ComponentOverrides) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComponentOverrides", ctx, eventID, overrides)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComponentOverrides indicates an expected call of UpdateComponentOverrides.
func (mr *MockEventRepositoryMockRecorder) UpdateComponentOverrides(ctx, eventID, overrides any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComponentOverrides", reflect.TypeOf((*MockEventRepository)(nil).UpdateComponentOverrides), ctx, eventID, overrides)
}

// UpdateStatus mocks base method.
func (m *MockEventRepository) UpdateStatus(ctx context.Context, id int64, status models.EventStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockEventRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockEventRepository)(nil).UpdateStatus), ctx, id, status)
}

// UpdateWithVersion mocks base method.
func (m *MockEventRepository) UpdateWithVersion(ctx context.Context, event *models.Event, expectedVersion int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithVersion", ctx, event, expectedVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithVersion indicates an expected call of UpdateWithVersion.
func (mr *MockEventRepositoryMockRecorder) UpdateWithVersion(ctx, event, expectedVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithVersion", reflect.TypeOf((*MockEventRepository)(nil).UpdateWithVersion), ctx, event, expectedVersion)
}
