// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/question_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/question_repository.go -destination=internal/testutil/mocks/repositories/mock_question_repository.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockQuestionRepository is a mock of QuestionRepository interface.
type MockQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepositoryMockRecorder
	isgomock struct{}
}

// MockQuestionRepositoryMockRecorder is the mock recorder for MockQuestionRepository.
type MockQuestionRepositoryMockRecorder struct {
	mock *MockQuestionRepository
}

// NewMockQuestionRepository creates a new mock instance.
func NewMockQuestionRepository(ctrl *gomock.Controller) *MockQuestionRepository {
	mock := &MockQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepository) EXPECT() *MockQuestionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQuestionRepository) Create(ctx context.Context, question *models.PreferenceQuestion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQuestionRepositoryMockRecorder) Create(ctx, question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuestionRepository)(nil).Create), ctx, question)
}

// Delete mocks base method.
func (m *MockQuestionRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQuestionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuestionRepository)(nil).Delete), ctx, id)
}

// GetByEventID mocks base method.
func (m *MockQuestionRepository) GetByEventID(ctx context.Context, eventID int64) ([]*models.PreferenceQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEventID", ctx, eventID)
	ret0, _ := ret[0].([]*models.PreferenceQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEventID indicates an expected call of GetByEventID.
func (mr *MockQuestionRepositoryMockRecorder) GetByEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEventID", reflect.TypeOf((*MockQuestionRepository)(nil).GetByEventID), ctx, eventID)
}

// GetByID mocks base method.
func (m *MockQuestionRepository) GetByID(ctx context.Context, id int64) (*models.PreferenceQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.PreferenceQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockQuestionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockQuestionRepository)(nil).GetByID), ctx, id)
}

// Reorder mocks base method.
func (m *MockQuestionRepository) Reorder(ctx context.Context, eventID int64, questionIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reorder", ctx, eventID, questionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reorder indicates an expected call of Reorder.
func (mr *MockQuestionRepositoryMockRecorder) Reorder(ctx, eventID, questionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reorder", reflect.TypeOf((*MockQuestionRepository)(nil).Reorder), ctx, eventID, questionIDs)
}

// Update mocks base method.
func (m *MockQuestionRepository) Update(ctx context.Context, question *models.PreferenceQuestion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuestionRepositoryMockRecorder) Update(ctx, question any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuestionRepository)(nil).Update), ctx, question)
}
