// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/template_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/template_repository.go -destination=internal/testutil/mocks/repositories/mock_template_repository.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	repositories "github.com/lenaxia/tinyrsvp/internal/db/repositories"
	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateRepository is a mock of TemplateRepository interface.
type MockTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateRepositoryMockRecorder
	isgomock struct{}
}

// MockTemplateRepositoryMockRecorder is the mock recorder for MockTemplateRepository.
type MockTemplateRepositoryMockRecorder struct {
	mock *MockTemplateRepository
}

// NewMockTemplateRepository creates a new mock instance.
func NewMockTemplateRepository(ctrl *gomock.Controller) *MockTemplateRepository {
	mock := &MockTemplateRepository{ctrl: ctrl}
	mock.recorder = &MockTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateRepository) EXPECT() *MockTemplateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTemplateRepository) Create(ctx context.Context, template *models.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTemplateRepositoryMockRecorder) Create(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTemplateRepository)(nil).Create), ctx, template)
}

// Delete mocks base method.
func (m *MockTemplateRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTemplateRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTemplateRepository)(nil).Delete), ctx, id)
}

// GetByEventAndType mocks base method.
func (m *MockTemplateRepository) GetByEventAndType(ctx context.Context, eventID int64, templateType models.TemplateType) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEventAndType", ctx, eventID, templateType)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEventAndType indicates an expected call of GetByEventAndType.
func (mr *MockTemplateRepositoryMockRecorder) GetByEventAndType(ctx, eventID, templateType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEventAndType", reflect.TypeOf((*MockTemplateRepository)(nil).GetByEventAndType), ctx, eventID, templateType)
}

// GetByID mocks base method.
func (m *MockTemplateRepository) GetByID(ctx context.Context, id int64) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTemplateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTemplateRepository)(nil).GetByID), ctx, id)
}

// GetByNameAndType mocks base method.
func (m *MockTemplateRepository) GetByNameAndType(ctx context.Context, name string, templateType models.TemplateType) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByNameAndType", ctx, name, templateType)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByNameAndType indicates an expected call of GetByNameAndType.
func (mr *MockTemplateRepositoryMockRecorder) GetByNameAndType(ctx, name, templateType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByNameAndType", reflect.TypeOf((*MockTemplateRepository)(nil).GetByNameAndType), ctx, name, templateType)
}

// GetComponentConfig mocks base method.
func (m *MockTemplateRepository) GetComponentConfig(ctx context.Context, templateID int64) (*models.ComponentConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentConfig", ctx, templateID)
	ret0, _ := ret[0].(*models.ComponentConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComponentConfig indicates an expected call of GetComponentConfig.
func (mr *MockTemplateRepositoryMockRecorder) GetComponentConfig(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentConfig", reflect.TypeOf((*MockTemplateRepository)(nil).GetComponentConfig), ctx, templateID)
}

// GetDefaultByType mocks base method.
func (m *MockTemplateRepository) GetDefaultByType(ctx context.Context, templateType models.TemplateType) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultByType", ctx, templateType)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultByType indicates an expected call of GetDefaultByType.
func (mr *MockTemplateRepositoryMockRecorder) GetDefaultByType(ctx, templateType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultByType", reflect.TypeOf((*MockTemplateRepository)(nil).GetDefaultByType), ctx, templateType)
}

// GetTemplatesByCategory mocks base method.
func (m *MockTemplateRepository) GetTemplatesByCategory(ctx context.Context, category models.TemplateCategory) ([]*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplatesByCategory", ctx, category)
	ret0, _ := ret[0].([]*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplatesByCategory indicates an expected call of GetTemplatesByCategory.
func (mr *MockTemplateRepositoryMockRecorder) GetTemplatesByCategory(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplatesByCategory", reflect.TypeOf((*MockTemplateRepository)(nil).GetTemplatesByCategory), ctx, category)
}

// IsTemplateInUse mocks base method.
func (m *MockTemplateRepository) IsTemplateInUse(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTemplateInUse", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTemplateInUse indicates an expected call of IsTemplateInUse.
func (mr *MockTemplateRepositoryMockRecorder) IsTemplateInUse(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTemplateInUse", reflect.TypeOf((*MockTemplateRepository)(nil).IsTemplateInUse), ctx, id)
}

// List mocks base method.
func (m *MockTemplateRepository) List(ctx context.Context, filters *repositories.TemplateFilters) ([]*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTemplateRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTemplateRepository)(nil).List), ctx, filters)
}

// ListThemes mocks base method.
func (m *MockTemplateRepository) ListThemes(ctx context.Context, templateType models.TemplateType, category *models.TemplateCategory) ([]*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListThemes", ctx, templateType, category)
	ret0, _ := ret[0].([]*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListThemes indicates an expected call of ListThemes.
func (mr *MockTemplateRepositoryMockRecorder) ListThemes(ctx, templateType, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListThemes", reflect.TypeOf((*MockTemplateRepository)(nil).ListThemes), ctx, templateType, category)
}

// SetActive mocks base method.
func (m *MockTemplateRepository) SetActive(ctx context.Context, id int64, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockTemplateRepositoryMockRecorder) SetActive(ctx, id, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockTemplateRepository)(nil).SetActive), ctx, id, active)
}

// SetDefault mocks base method.
func (m *MockTemplateRepository) SetDefault(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefault", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefault indicates an expected call of SetDefault.
func (mr *MockTemplateRepositoryMockRecorder) SetDefault(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefault", reflect.TypeOf((*MockTemplateRepository)(nil).SetDefault), ctx, id)
}

// Update mocks base method.
func (m *MockTemplateRepository) Update(ctx context.Context, template *models.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTemplateRepositoryMockRecorder) Update(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTemplateRepository)(nil).Update), ctx, template)
}

// UpdateComponentConfig mocks base method.
func (m *MockTemplateRepository) UpdateComponentConfig(ctx context.Context, templateID int64, config *models.ComponentConfiguration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComponentConfig", ctx, templateID, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComponentConfig indicates an expected call of UpdateComponentConfig.
func (mr *MockTemplateRepositoryMockRecorder) UpdateComponentConfig(ctx, templateID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComponentConfig", reflect.TypeOf((*MockTemplateRepository)(nil).UpdateComponentConfig), ctx, templateID, config)
}

// ValidateComponentConfig mocks base method.
func (m *MockTemplateRepository) ValidateComponentConfig(ctx context.Context, config *models.ComponentConfiguration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateComponentConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateComponentConfig indicates an expected call of ValidateComponentConfig.
func (mr *MockTemplateRepositoryMockRecorder) ValidateComponentConfig(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateComponentConfig", reflect.TypeOf((*MockTemplateRepository)(nil).ValidateComponentConfig), ctx, config)
}
