// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/permissions.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/permissions.go -destination=internal/testutil/mocks/mock_authorization.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizationChecker is a mock of AuthorizationChecker interface.
type MockAuthorizationChecker struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationCheckerMockRecorder
	isgomock struct{}
}

// MockAuthorizationCheckerMockRecorder is the mock recorder for MockAuthorizationChecker.
type MockAuthorizationCheckerMockRecorder struct {
	mock *MockAuthorizationChecker
}

// NewMockAuthorizationChecker creates a new mock instance.
func NewMockAuthorizationChecker(ctrl *gomock.Controller) *MockAuthorizationChecker {
	mock := &MockAuthorizationChecker{ctrl: ctrl}
	mock.recorder = &MockAuthorizationCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationChecker) EXPECT() *MockAuthorizationCheckerMockRecorder {
	return m.recorder
}

// CanConfigureSystem mocks base method.
func (m *MockAuthorizationChecker) CanConfigureSystem(ctx context.Context, user *models.User) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanConfigureSystem", ctx, user)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanConfigureSystem indicates an expected call of CanConfigureSystem.
func (mr *MockAuthorizationCheckerMockRecorder) CanConfigureSystem(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanConfigureSystem", reflect.TypeOf((*MockAuthorizationChecker)(nil).CanConfigureSystem), ctx, user)
}

// CanCreateEvent mocks base method.
func (m *MockAuthorizationChecker) CanCreateEvent(ctx context.Context, user *models.User) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanCreateEvent", ctx, user)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanCreateEvent indicates an expected call of CanCreateEvent.
func (mr *MockAuthorizationCheckerMockRecorder) CanCreateEvent(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanCreateEvent", reflect.TypeOf((*MockAuthorizationChecker)(nil).CanCreateEvent), ctx, user)
}

// CanDeleteEvent mocks base method.
func (m *MockAuthorizationChecker) CanDeleteEvent(ctx context.Context, user *models.User, event *models.Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanDeleteEvent", ctx, user, event)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanDeleteEvent indicates an expected call of CanDeleteEvent.
func (mr *MockAuthorizationCheckerMockRecorder) CanDeleteEvent(ctx, user, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanDeleteEvent", reflect.TypeOf((*MockAuthorizationChecker)(nil).CanDeleteEvent), ctx, user, event)
}

// CanEditEvent mocks base method.
func (m *MockAuthorizationChecker) CanEditEvent(ctx context.Context, user *models.User, event *models.Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanEditEvent", ctx, user, event)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanEditEvent indicates an expected call of CanEditEvent.
func (mr *MockAuthorizationCheckerMockRecorder) CanEditEvent(ctx, user, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanEditEvent", reflect.TypeOf((*MockAuthorizationChecker)(nil).CanEditEvent), ctx, user, event)
}

// CanManageInvites mocks base method.
func (m *MockAuthorizationChecker) CanManageInvites(ctx context.Context, user *models.User, event *models.Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanManageInvites", ctx, user, event)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanManageInvites indicates an expected call of CanManageInvites.
func (mr *MockAuthorizationCheckerMockRecorder) CanManageInvites(ctx, user, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanManageInvites", reflect.TypeOf((*MockAuthorizationChecker)(nil).CanManageInvites), ctx, user, event)
}

// CanManageUsers mocks base method.
func (m *MockAuthorizationChecker) CanManageUsers(ctx context.Context, user *models.User) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanManageUsers", ctx, user)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanManageUsers indicates an expected call of CanManageUsers.
func (mr *MockAuthorizationCheckerMockRecorder) CanManageUsers(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanManageUsers", reflect.TypeOf((*MockAuthorizationChecker)(nil).CanManageUsers), ctx, user)
}

// CanViewEvent mocks base method.
func (m *MockAuthorizationChecker) CanViewEvent(ctx context.Context, user *models.User, event *models.Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanViewEvent", ctx, user, event)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanViewEvent indicates an expected call of CanViewEvent.
func (mr *MockAuthorizationCheckerMockRecorder) CanViewEvent(ctx, user, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanViewEvent", reflect.TypeOf((*MockAuthorizationChecker)(nil).CanViewEvent), ctx, user, event)
}

// CanViewRSVPs mocks base method.
func (m *MockAuthorizationChecker) CanViewRSVPs(ctx context.Context, user *models.User, event *models.Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanViewRSVPs", ctx, user, event)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanViewRSVPs indicates an expected call of CanViewRSVPs.
func (mr *MockAuthorizationCheckerMockRecorder) CanViewRSVPs(ctx, user, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanViewRSVPs", reflect.TypeOf((*MockAuthorizationChecker)(nil).CanViewRSVPs), ctx, user, event)
}

// IsAdmin mocks base method.
func (m *MockAuthorizationChecker) IsAdmin(user *models.User) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", user)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockAuthorizationCheckerMockRecorder) IsAdmin(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockAuthorizationChecker)(nil).IsAdmin), user)
}

// IsEventManager mocks base method.
func (m *MockAuthorizationChecker) IsEventManager(user *models.User) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEventManager", user)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEventManager indicates an expected call of IsEventManager.
func (mr *MockAuthorizationCheckerMockRecorder) IsEventManager(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEventManager", reflect.TypeOf((*MockAuthorizationChecker)(nil).IsEventManager), user)
}
