// Code generated by MockGen. DO NOT EDIT.
// Source: internal/templates/validator.go
//
// Generated by this command:
//
//	mockgen -source=internal/templates/validator.go -destination=internal/testutil/mocks/mock_template_validator.go -package=mocks -mock_names=Validator=MockTemplateValidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateValidator is a mock of Validator interface.
type MockTemplateValidator struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateValidatorMockRecorder
	isgomock struct{}
}

// MockTemplateValidatorMockRecorder is the mock recorder for MockTemplateValidator.
type MockTemplateValidatorMockRecorder struct {
	mock *MockTemplateValidator
}

// NewMockTemplateValidator creates a new mock instance.
func NewMockTemplateValidator(ctrl *gomock.Controller) *MockTemplateValidator {
	mock := &MockTemplateValidator{ctrl: ctrl}
	mock.recorder = &MockTemplateValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateValidator) EXPECT() *MockTemplateValidatorMockRecorder {
	return m.recorder
}

// ValidateSize mocks base method.
func (m *MockTemplateValidator) ValidateSize(content string, maxBytes int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSize", content, maxBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSize indicates an expected call of ValidateSize.
func (mr *MockTemplateValidatorMockRecorder) ValidateSize(content, maxBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSize", reflect.TypeOf((*MockTemplateValidator)(nil).ValidateSize), content, maxBytes)
}

// ValidateSyntax mocks base method.
func (m *MockTemplateValidator) ValidateSyntax(content string, templateType models.TemplateType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSyntax", content, templateType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSyntax indicates an expected call of ValidateSyntax.
func (mr *MockTemplateValidatorMockRecorder) ValidateSyntax(content, templateType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSyntax", reflect.TypeOf((*MockTemplateValidator)(nil).ValidateSyntax), content, templateType)
}

// ValidateTemplate mocks base method.
func (m *MockTemplateValidator) ValidateTemplate(tmpl *models.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTemplate", tmpl)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateTemplate indicates an expected call of ValidateTemplate.
func (mr *MockTemplateValidatorMockRecorder) ValidateTemplate(tmpl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTemplate", reflect.TypeOf((*MockTemplateValidator)(nil).ValidateTemplate), tmpl)
}

// ValidateVariables mocks base method.
func (m *MockTemplateValidator) ValidateVariables(content string, allowedVars []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateVariables", content, allowedVars)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateVariables indicates an expected call of ValidateVariables.
func (mr *MockTemplateValidatorMockRecorder) ValidateVariables(content, allowedVars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateVariables", reflect.TypeOf((*MockTemplateValidator)(nil).ValidateVariables), content, allowedVars)
}
