// Code generated by MockGen. DO NOT EDIT.
// Source: internal/events/validator.go
//
// Generated by this command:
//
//	mockgen -source=internal/events/validator.go -destination=internal/testutil/mocks/mock_event_validator.go -package=mocks -mock_names=Validator=MockEventValidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockEventValidator is a mock of Validator interface.
type MockEventValidator struct {
	ctrl     *gomock.Controller
	recorder *MockEventValidatorMockRecorder
	isgomock struct{}
}

// MockEventValidatorMockRecorder is the mock recorder for MockEventValidator.
type MockEventValidatorMockRecorder struct {
	mock *MockEventValidator
}

// NewMockEventValidator creates a new mock instance.
func NewMockEventValidator(ctrl *gomock.Controller) *MockEventValidator {
	mock := &MockEventValidator{ctrl: ctrl}
	mock.recorder = &MockEventValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventValidator) EXPECT() *MockEventValidatorMockRecorder {
	return m.recorder
}

// ValidateCreate mocks base method.
func (m *MockEventValidator) ValidateCreate(ctx context.Context, event *models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCreate", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCreate indicates an expected call of ValidateCreate.
func (mr *MockEventValidatorMockRecorder) ValidateCreate(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCreate", reflect.TypeOf((*MockEventValidator)(nil).ValidateCreate), ctx, event)
}

// ValidateStateTransition mocks base method.
func (m *MockEventValidator) ValidateStateTransition(from, to models.EventStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateStateTransition", from, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateStateTransition indicates an expected call of ValidateStateTransition.
func (mr *MockEventValidatorMockRecorder) ValidateStateTransition(from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateStateTransition", reflect.TypeOf((*MockEventValidator)(nil).ValidateStateTransition), from, to)
}

// ValidateUpdate mocks base method.
func (m *MockEventValidator) ValidateUpdate(ctx context.Context, event *models.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUpdate", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateUpdate indicates an expected call of ValidateUpdate.
func (mr *MockEventValidatorMockRecorder) ValidateUpdate(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUpdate", reflect.TypeOf((*MockEventValidator)(nil).ValidateUpdate), ctx, event)
}
