// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/email_queue_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/email_queue_repository.go -destination=internal/testutil/mocks/mock_email_queue_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	repositories "github.com/lenaxia/tinyrsvp/internal/db/repositories"
	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailQueueRepository is a mock of EmailQueueRepository interface.
type MockEmailQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailQueueRepositoryMockRecorder
	isgomock struct{}
}

// MockEmailQueueRepositoryMockRecorder is the mock recorder for MockEmailQueueRepository.
type MockEmailQueueRepositoryMockRecorder struct {
	mock *MockEmailQueueRepository
}

// NewMockEmailQueueRepository creates a new mock instance.
func NewMockEmailQueueRepository(ctrl *gomock.Controller) *MockEmailQueueRepository {
	mock := &MockEmailQueueRepository{ctrl: ctrl}
	mock.recorder = &MockEmailQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailQueueRepository) EXPECT() *MockEmailQueueRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEmailQueueRepository) Create(ctx context.Context, email *models.EmailQueue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEmailQueueRepositoryMockRecorder) Create(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmailQueueRepository)(nil).Create), ctx, email)
}

// GetByID mocks base method.
func (m *MockEmailQueueRepository) GetByID(ctx context.Context, id int64) (*models.EmailQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.EmailQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEmailQueueRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEmailQueueRepository)(nil).GetByID), ctx, id)
}

// GetByRecipient mocks base method.
func (m *MockEmailQueueRepository) GetByRecipient(ctx context.Context, email string, limit int) ([]*models.EmailQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRecipient", ctx, email, limit)
	ret0, _ := ret[0].([]*models.EmailQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRecipient indicates an expected call of GetByRecipient.
func (mr *MockEmailQueueRepositoryMockRecorder) GetByRecipient(ctx, email, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRecipient", reflect.TypeOf((*MockEmailQueueRepository)(nil).GetByRecipient), ctx, email, limit)
}

// GetByStatus mocks base method.
func (m *MockEmailQueueRepository) GetByStatus(ctx context.Context, status models.EmailStatus, limit int) ([]*models.EmailQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStatus", ctx, status, limit)
	ret0, _ := ret[0].([]*models.EmailQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStatus indicates an expected call of GetByStatus.
func (mr *MockEmailQueueRepositoryMockRecorder) GetByStatus(ctx, status, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStatus", reflect.TypeOf((*MockEmailQueueRepository)(nil).GetByStatus), ctx, status, limit)
}

// GetPending mocks base method.
func (m *MockEmailQueueRepository) GetPending(ctx context.Context, maxCount int) ([]*models.EmailQueue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPending", ctx, maxCount)
	ret0, _ := ret[0].([]*models.EmailQueue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPending indicates an expected call of GetPending.
func (mr *MockEmailQueueRepositoryMockRecorder) GetPending(ctx, maxCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPending", reflect.TypeOf((*MockEmailQueueRepository)(nil).GetPending), ctx, maxCount)
}

// GetStats mocks base method.
func (m *MockEmailQueueRepository) GetStats(ctx context.Context) (*repositories.EmailQueueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(*repositories.EmailQueueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockEmailQueueRepositoryMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockEmailQueueRepository)(nil).GetStats), ctx)
}

// IncrementAttempts mocks base method.
func (m *MockEmailQueueRepository) IncrementAttempts(ctx context.Context, id int64, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAttempts", ctx, id, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAttempts indicates an expected call of IncrementAttempts.
func (mr *MockEmailQueueRepositoryMockRecorder) IncrementAttempts(ctx, id, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAttempts", reflect.TypeOf((*MockEmailQueueRepository)(nil).IncrementAttempts), ctx, id, errorMsg)
}

// MarkCancelled mocks base method.
func (m *MockEmailQueueRepository) MarkCancelled(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCancelled", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCancelled indicates an expected call of MarkCancelled.
func (mr *MockEmailQueueRepositoryMockRecorder) MarkCancelled(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCancelled", reflect.TypeOf((*MockEmailQueueRepository)(nil).MarkCancelled), ctx, id)
}

// MarkFailed mocks base method.
func (m *MockEmailQueueRepository) MarkFailed(ctx context.Context, id int64, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockEmailQueueRepositoryMockRecorder) MarkFailed(ctx, id, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockEmailQueueRepository)(nil).MarkFailed), ctx, id, errorMsg)
}

// MarkSending mocks base method.
func (m *MockEmailQueueRepository) MarkSending(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSending", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSending indicates an expected call of MarkSending.
func (mr *MockEmailQueueRepositoryMockRecorder) MarkSending(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSending", reflect.TypeOf((*MockEmailQueueRepository)(nil).MarkSending), ctx, id)
}

// MarkSent mocks base method.
func (m *MockEmailQueueRepository) MarkSent(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSent indicates an expected call of MarkSent.
func (mr *MockEmailQueueRepositoryMockRecorder) MarkSent(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSent", reflect.TypeOf((*MockEmailQueueRepository)(nil).MarkSent), ctx, id)
}

// Reschedule mocks base method.
func (m *MockEmailQueueRepository) Reschedule(ctx context.Context, id int64, scheduledFor time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reschedule", ctx, id, scheduledFor)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reschedule indicates an expected call of Reschedule.
func (mr *MockEmailQueueRepositoryMockRecorder) Reschedule(ctx, id, scheduledFor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reschedule", reflect.TypeOf((*MockEmailQueueRepository)(nil).Reschedule), ctx, id, scheduledFor)
}

// UpdateStatus mocks base method.
func (m *MockEmailQueueRepository) UpdateStatus(ctx context.Context, id int64, status models.EmailStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockEmailQueueRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockEmailQueueRepository)(nil).UpdateStatus), ctx, id, status)
}
