// Code generated by MockGen. DO NOT EDIT.
// Source: internal/invites/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/invites/service.go -destination=internal/testutil/mocks/mock_invite_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	repositories "github.com/lenaxia/tinyrsvp/internal/db/repositories"
	invites "github.com/lenaxia/tinyrsvp/internal/invites"
	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockInviteService is a mock of InviteService interface.
type MockInviteService struct {
	ctrl     *gomock.Controller
	recorder *MockInviteServiceMockRecorder
	isgomock struct{}
}

// MockInviteServiceMockRecorder is the mock recorder for MockInviteService.
type MockInviteServiceMockRecorder struct {
	mock *MockInviteService
}

// NewMockInviteService creates a new mock instance.
func NewMockInviteService(ctrl *gomock.Controller) *MockInviteService {
	mock := &MockInviteService{ctrl: ctrl}
	mock.recorder = &MockInviteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviteService) EXPECT() *MockInviteServiceMockRecorder {
	return m.recorder
}

// CleanupExpiredTokens mocks base method.
func (m *MockInviteService) CleanupExpiredTokens(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredTokens", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredTokens indicates an expected call of CleanupExpiredTokens.
func (mr *MockInviteServiceMockRecorder) CleanupExpiredTokens(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredTokens", reflect.TypeOf((*MockInviteService)(nil).CleanupExpiredTokens), ctx)
}

// CreateInvite mocks base method.
func (m *MockInviteService) CreateInvite(ctx context.Context, eventID int64, name, email *string, maxPlusOnes int, expiresAt time.Time) (*models.Invite, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", ctx, eventID, name, email, maxPlusOnes, expiresAt)
	ret0, _ := ret[0].(*models.Invite)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockInviteServiceMockRecorder) CreateInvite(ctx, eventID, name, email, maxPlusOnes, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockInviteService)(nil).CreateInvite), ctx, eventID, name, email, maxPlusOnes, expiresAt)
}

// CreateManualInvite mocks base method.
func (m *MockInviteService) CreateManualInvite(ctx context.Context, req *invites.CreateManualInviteRequest, expiresAt time.Time) (*invites.CreateManualInviteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManualInvite", ctx, req, expiresAt)
	ret0, _ := ret[0].(*invites.CreateManualInviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateManualInvite indicates an expected call of CreateManualInvite.
func (mr *MockInviteServiceMockRecorder) CreateManualInvite(ctx, req, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManualInvite", reflect.TypeOf((*MockInviteService)(nil).CreateManualInvite), ctx, req, expiresAt)
}

// DeleteInvite mocks base method.
func (m *MockInviteService) DeleteInvite(ctx context.Context, inviteID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvite", ctx, inviteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvite indicates an expected call of DeleteInvite.
func (mr *MockInviteServiceMockRecorder) DeleteInvite(ctx, inviteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvite", reflect.TypeOf((*MockInviteService)(nil).DeleteInvite), ctx, inviteID)
}

// GetInviteByID mocks base method.
func (m *MockInviteService) GetInviteByID(ctx context.Context, id int64) (*models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInviteByID", ctx, id)
	ret0, _ := ret[0].(*models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInviteByID indicates an expected call of GetInviteByID.
func (mr *MockInviteServiceMockRecorder) GetInviteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInviteByID", reflect.TypeOf((*MockInviteService)(nil).GetInviteByID), ctx, id)
}

// GetInviteByToken mocks base method.
func (m *MockInviteService) GetInviteByToken(ctx context.Context, token string) (*models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInviteByToken", ctx, token)
	ret0, _ := ret[0].(*models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInviteByToken indicates an expected call of GetInviteByToken.
func (mr *MockInviteServiceMockRecorder) GetInviteByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInviteByToken", reflect.TypeOf((*MockInviteService)(nil).GetInviteByToken), ctx, token)
}

// ImportCSV mocks base method.
func (m *MockInviteService) ImportCSV(ctx context.Context, eventID int64, csvData []byte, defaultMaxPlusOnes int, expiresAt time.Time) (*invites.ImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportCSV", ctx, eventID, csvData, defaultMaxPlusOnes, expiresAt)
	ret0, _ := ret[0].(*invites.ImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportCSV indicates an expected call of ImportCSV.
func (mr *MockInviteServiceMockRecorder) ImportCSV(ctx, eventID, csvData, defaultMaxPlusOnes, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportCSV", reflect.TypeOf((*MockInviteService)(nil).ImportCSV), ctx, eventID, csvData, defaultMaxPlusOnes, expiresAt)
}

// ListInvites mocks base method.
func (m *MockInviteService) ListInvites(ctx context.Context, req *invites.ListInvitesRequest) (*invites.ListInvitesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvites", ctx, req)
	ret0, _ := ret[0].(*invites.ListInvitesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvites indicates an expected call of ListInvites.
func (mr *MockInviteServiceMockRecorder) ListInvites(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvites", reflect.TypeOf((*MockInviteService)(nil).ListInvites), ctx, req)
}

// ListInvitesByEventID mocks base method.
func (m *MockInviteService) ListInvitesByEventID(ctx context.Context, eventID int64, filters repositories.InviteFilters) ([]*models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitesByEventID", ctx, eventID, filters)
	ret0, _ := ret[0].([]*models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitesByEventID indicates an expected call of ListInvitesByEventID.
func (mr *MockInviteServiceMockRecorder) ListInvitesByEventID(ctx, eventID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitesByEventID", reflect.TypeOf((*MockInviteService)(nil).ListInvitesByEventID), ctx, eventID, filters)
}

// MarkInviteResponded mocks base method.
func (m *MockInviteService) MarkInviteResponded(ctx context.Context, inviteID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkInviteResponded", ctx, inviteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkInviteResponded indicates an expected call of MarkInviteResponded.
func (mr *MockInviteServiceMockRecorder) MarkInviteResponded(ctx, inviteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkInviteResponded", reflect.TypeOf((*MockInviteService)(nil).MarkInviteResponded), ctx, inviteID)
}

// MarkInviteSent mocks base method.
func (m *MockInviteService) MarkInviteSent(ctx context.Context, inviteID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkInviteSent", ctx, inviteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkInviteSent indicates an expected call of MarkInviteSent.
func (mr *MockInviteServiceMockRecorder) MarkInviteSent(ctx, inviteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkInviteSent", reflect.TypeOf((*MockInviteService)(nil).MarkInviteSent), ctx, inviteID)
}

// MarkInviteViewed mocks base method.
func (m *MockInviteService) MarkInviteViewed(ctx context.Context, inviteID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkInviteViewed", ctx, inviteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkInviteViewed indicates an expected call of MarkInviteViewed.
func (mr *MockInviteServiceMockRecorder) MarkInviteViewed(ctx, inviteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkInviteViewed", reflect.TypeOf((*MockInviteService)(nil).MarkInviteViewed), ctx, inviteID)
}

// RegenerateToken mocks base method.
func (m *MockInviteService) RegenerateToken(ctx context.Context, inviteID int64) (*invites.RegenerateTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegenerateToken", ctx, inviteID)
	ret0, _ := ret[0].(*invites.RegenerateTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegenerateToken indicates an expected call of RegenerateToken.
func (mr *MockInviteServiceMockRecorder) RegenerateToken(ctx, inviteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegenerateToken", reflect.TypeOf((*MockInviteService)(nil).RegenerateToken), ctx, inviteID)
}

// RevokeInvite mocks base method.
func (m *MockInviteService) RevokeInvite(ctx context.Context, req *invites.RevokeInviteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeInvite", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeInvite indicates an expected call of RevokeInvite.
func (mr *MockInviteServiceMockRecorder) RevokeInvite(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeInvite", reflect.TypeOf((*MockInviteService)(nil).RevokeInvite), ctx, req)
}

// SendInvite mocks base method.
func (m *MockInviteService) SendInvite(ctx context.Context, req *invites.SendInviteRequest, emailRepo repositories.EmailQueueRepository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInvite", ctx, req, emailRepo)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInvite indicates an expected call of SendInvite.
func (mr *MockInviteServiceMockRecorder) SendInvite(ctx, req, emailRepo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInvite", reflect.TypeOf((*MockInviteService)(nil).SendInvite), ctx, req, emailRepo)
}

// UnsubscribeFromReminders mocks base method.
func (m *MockInviteService) UnsubscribeFromReminders(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeFromReminders", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeFromReminders indicates an expected call of UnsubscribeFromReminders.
func (mr *MockInviteServiceMockRecorder) UnsubscribeFromReminders(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeFromReminders", reflect.TypeOf((*MockInviteService)(nil).UnsubscribeFromReminders), ctx, token)
}

// UpdateInvite mocks base method.
func (m *MockInviteService) UpdateInvite(ctx context.Context, req *invites.UpdateInviteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInvite", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInvite indicates an expected call of UpdateInvite.
func (mr *MockInviteServiceMockRecorder) UpdateInvite(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInvite", reflect.TypeOf((*MockInviteService)(nil).UpdateInvite), ctx, req)
}
