// Code generated by MockGen. DO NOT EDIT.
// Source: internal/email/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/email/service.go -destination=internal/testutil/mocks/mock_email_service.go -package=mocks -mock_names=Service=MockEmailService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailService is a mock of Service interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
	isgomock struct{}
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendConfirmationEmail mocks base method.
func (m *MockEmailService) SendConfirmationEmail(ctx context.Context, token string, rsvp *models.RSVP, invite *models.Invite, event *models.Event, answers []*models.RSVPAnswer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirmationEmail", ctx, token, rsvp, invite, event, answers)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirmationEmail indicates an expected call of SendConfirmationEmail.
func (mr *MockEmailServiceMockRecorder) SendConfirmationEmail(ctx, token, rsvp, invite, event, answers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirmationEmail", reflect.TypeOf((*MockEmailService)(nil).SendConfirmationEmail), ctx, token, rsvp, invite, event, answers)
}
