// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/invite_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/invite_repository.go -destination=internal/testutil/mocks/mock_invite_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	repositories "github.com/lenaxia/tinyrsvp/internal/db/repositories"
	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockInviteRepository is a mock of InviteRepository interface.
type MockInviteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInviteRepositoryMockRecorder
	isgomock struct{}
}

// MockInviteRepositoryMockRecorder is the mock recorder for MockInviteRepository.
type MockInviteRepositoryMockRecorder struct {
	mock *MockInviteRepository
}

// NewMockInviteRepository creates a new mock instance.
func NewMockInviteRepository(ctrl *gomock.Controller) *MockInviteRepository {
	mock := &MockInviteRepository{ctrl: ctrl}
	mock.recorder = &MockInviteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviteRepository) EXPECT() *MockInviteRepositoryMockRecorder {
	return m.recorder
}

// CountByEventID mocks base method.
func (m *MockInviteRepository) CountByEventID(ctx context.Context, eventID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByEventID", ctx, eventID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByEventID indicates an expected call of CountByEventID.
func (mr *MockInviteRepositoryMockRecorder) CountByEventID(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByEventID", reflect.TypeOf((*MockInviteRepository)(nil).CountByEventID), ctx, eventID)
}

// CountByEventIDWithFilters mocks base method.
func (m *MockInviteRepository) CountByEventIDWithFilters(ctx context.Context, eventID int64, filters repositories.InviteFilters) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByEventIDWithFilters", ctx, eventID, filters)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByEventIDWithFilters indicates an expected call of CountByEventIDWithFilters.
func (mr *MockInviteRepositoryMockRecorder) CountByEventIDWithFilters(ctx, eventID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByEventIDWithFilters", reflect.TypeOf((*MockInviteRepository)(nil).CountByEventIDWithFilters), ctx, eventID, filters)
}

// CountInvites mocks base method.
func (m *MockInviteRepository) CountInvites(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountInvites", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountInvites indicates an expected call of CountInvites.
func (mr *MockInviteRepositoryMockRecorder) CountInvites(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountInvites", reflect.TypeOf((*MockInviteRepository)(nil).CountInvites), ctx)
}

// Create mocks base method.
func (m *MockInviteRepository) Create(ctx context.Context, invite *models.Invite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInviteRepositoryMockRecorder) Create(ctx, invite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInviteRepository)(nil).Create), ctx, invite)
}

// CreateBatch mocks base method.
func (m *MockInviteRepository) CreateBatch(ctx context.Context, invites []*models.Invite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, invites)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockInviteRepositoryMockRecorder) CreateBatch(ctx, invites any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockInviteRepository)(nil).CreateBatch), ctx, invites)
}

// Delete mocks base method.
func (m *MockInviteRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInviteRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInviteRepository)(nil).Delete), ctx, id)
}

// DeleteExpired mocks base method.
func (m *MockInviteRepository) DeleteExpired(ctx context.Context, before time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockInviteRepositoryMockRecorder) DeleteExpired(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockInviteRepository)(nil).DeleteExpired), ctx, before)
}

// FindDuplicateEmails mocks base method.
func (m *MockInviteRepository) FindDuplicateEmails(ctx context.Context, eventID int64, emails []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDuplicateEmails", ctx, eventID, emails)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDuplicateEmails indicates an expected call of FindDuplicateEmails.
func (mr *MockInviteRepositoryMockRecorder) FindDuplicateEmails(ctx, eventID, emails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDuplicateEmails", reflect.TypeOf((*MockInviteRepository)(nil).FindDuplicateEmails), ctx, eventID, emails)
}

// GetByEventIDs mocks base method.
func (m *MockInviteRepository) GetByEventIDs(ctx context.Context, eventIDs []int64) ([]*models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEventIDs", ctx, eventIDs)
	ret0, _ := ret[0].([]*models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEventIDs indicates an expected call of GetByEventIDs.
func (mr *MockInviteRepositoryMockRecorder) GetByEventIDs(ctx, eventIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEventIDs", reflect.TypeOf((*MockInviteRepository)(nil).GetByEventIDs), ctx, eventIDs)
}

// GetByID mocks base method.
func (m *MockInviteRepository) GetByID(ctx context.Context, id int64) (*models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInviteRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInviteRepository)(nil).GetByID), ctx, id)
}

// GetByTokenHash mocks base method.
func (m *MockInviteRepository) GetByTokenHash(ctx context.Context, tokenHash string) (*models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockInviteRepositoryMockRecorder) GetByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockInviteRepository)(nil).GetByTokenHash), ctx, tokenHash)
}

// GetStats mocks base method.
func (m *MockInviteRepository) GetStats(ctx context.Context, eventID int64) (*repositories.InviteStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, eventID)
	ret0, _ := ret[0].(*repositories.InviteStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockInviteRepositoryMockRecorder) GetStats(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockInviteRepository)(nil).GetStats), ctx, eventID)
}

// ListByEventID mocks base method.
func (m *MockInviteRepository) ListByEventID(ctx context.Context, eventID int64, filters repositories.InviteFilters) ([]*models.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEventID", ctx, eventID, filters)
	ret0, _ := ret[0].([]*models.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByEventID indicates an expected call of ListByEventID.
func (mr *MockInviteRepositoryMockRecorder) ListByEventID(ctx, eventID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEventID", reflect.TypeOf((*MockInviteRepository)(nil).ListByEventID), ctx, eventID, filters)
}

// Update mocks base method.
func (m *MockInviteRepository) Update(ctx context.Context, invite *models.Invite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, invite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInviteRepositoryMockRecorder) Update(ctx, invite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInviteRepository)(nil).Update), ctx, invite)
}
