// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/answer_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/answer_repository.go -destination=internal/testutil/mocks/mock_answer_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAnswerRepository is a mock of AnswerRepository interface.
type MockAnswerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnswerRepositoryMockRecorder
	isgomock struct{}
}

// MockAnswerRepositoryMockRecorder is the mock recorder for MockAnswerRepository.
type MockAnswerRepositoryMockRecorder struct {
	mock *MockAnswerRepository
}

// NewMockAnswerRepository creates a new mock instance.
func NewMockAnswerRepository(ctrl *gomock.Controller) *MockAnswerRepository {
	mock := &MockAnswerRepository{ctrl: ctrl}
	mock.recorder = &MockAnswerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnswerRepository) EXPECT() *MockAnswerRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAnswerRepository) Create(ctx context.Context, answer *models.RSVPAnswer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAnswerRepositoryMockRecorder) Create(ctx, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAnswerRepository)(nil).Create), ctx, answer)
}

// DeleteByRSVPID mocks base method.
func (m *MockAnswerRepository) DeleteByRSVPID(ctx context.Context, rsvpID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRSVPID", ctx, rsvpID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByRSVPID indicates an expected call of DeleteByRSVPID.
func (mr *MockAnswerRepositoryMockRecorder) DeleteByRSVPID(ctx, rsvpID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRSVPID", reflect.TypeOf((*MockAnswerRepository)(nil).DeleteByRSVPID), ctx, rsvpID)
}

// GetByQuestionID mocks base method.
func (m *MockAnswerRepository) GetByQuestionID(ctx context.Context, questionID int64) ([]*models.RSVPAnswer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByQuestionID", ctx, questionID)
	ret0, _ := ret[0].([]*models.RSVPAnswer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByQuestionID indicates an expected call of GetByQuestionID.
func (mr *MockAnswerRepositoryMockRecorder) GetByQuestionID(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByQuestionID", reflect.TypeOf((*MockAnswerRepository)(nil).GetByQuestionID), ctx, questionID)
}

// GetByRSVPID mocks base method.
func (m *MockAnswerRepository) GetByRSVPID(ctx context.Context, rsvpID int64) ([]*models.RSVPAnswer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRSVPID", ctx, rsvpID)
	ret0, _ := ret[0].([]*models.RSVPAnswer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRSVPID indicates an expected call of GetByRSVPID.
func (mr *MockAnswerRepositoryMockRecorder) GetByRSVPID(ctx, rsvpID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRSVPID", reflect.TypeOf((*MockAnswerRepository)(nil).GetByRSVPID), ctx, rsvpID)
}

// Update mocks base method.
func (m *MockAnswerRepository) Update(ctx context.Context, answer *models.RSVPAnswer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAnswerRepositoryMockRecorder) Update(ctx, answer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAnswerRepository)(nil).Update), ctx, answer)
}
