// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/repositories/config_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/repositories/config_repository.go -destination=internal/testutil/mocks/mock_config_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/lenaxia/tinyrsvp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigRepository is a mock of ConfigRepository interface.
type MockConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockConfigRepositoryMockRecorder is the mock recorder for MockConfigRepository.
type MockConfigRepositoryMockRecorder struct {
	mock *MockConfigRepository
}

// NewMockConfigRepository creates a new mock instance.
func NewMockConfigRepository(ctrl *gomock.Controller) *MockConfigRepository {
	mock := &MockConfigRepository{ctrl: ctrl}
	mock.recorder = &MockConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigRepository) EXPECT() *MockConfigRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockConfigRepository) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConfigRepositoryMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConfigRepository)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockConfigRepository) Get(ctx context.Context, key string) (*models.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*models.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfigRepositoryMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigRepository)(nil).Get), ctx, key)
}

// GetAll mocks base method.
func (m *MockConfigRepository) GetAll(ctx context.Context) ([]*models.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*models.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockConfigRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockConfigRepository)(nil).GetAll), ctx)
}

// GetHMACSecret mocks base method.
func (m *MockConfigRepository) GetHMACSecret(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHMACSecret", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHMACSecret indicates an expected call of GetHMACSecret.
func (mr *MockConfigRepositoryMockRecorder) GetHMACSecret(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHMACSecret", reflect.TypeOf((*MockConfigRepository)(nil).GetHMACSecret), ctx)
}

// Set mocks base method.
func (m *MockConfigRepository) Set(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockConfigRepositoryMockRecorder) Set(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockConfigRepository)(nil).Set), ctx, key, value)
}

// SetHMACSecret mocks base method.
func (m *MockConfigRepository) SetHMACSecret(ctx context.Context, secret []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHMACSecret", ctx, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHMACSecret indicates an expected call of SetHMACSecret.
func (mr *MockConfigRepositoryMockRecorder) SetHMACSecret(ctx, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHMACSecret", reflect.TypeOf((*MockConfigRepository)(nil).SetHMACSecret), ctx, secret)
}
